version: "3.9"

services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi-app
    ports:
      - "8080:8080"
    volumes:
      - .:/app
      - ./uploads:/app/uploads
    command: >
      uvicorn main:app --host 0.0.0.0 --port 8080 --reload
